from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.chat_completion_request_message_content_part_text import ChatCompletionRequestMessageContentPartText
from openapi_server import util

from openapi_server.models.chat_completion_request_message_content_part_text import ChatCompletionRequestMessageContentPartText  # noqa: E501

class ChatCompletionRequestToolMessageContentPart(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type=None, text=None):  # noqa: E501
        """ChatCompletionRequestToolMessageContentPart - a model defined in OpenAPI

        :param type: The type of this ChatCompletionRequestToolMessageContentPart.  # noqa: E501
        :type type: str
        :param text: The text of this ChatCompletionRequestToolMessageContentPart.  # noqa: E501
        :type text: str
        """
        self.openapi_types = {
            'type': str,
            'text': str
        }

        self.attribute_map = {
            'type': 'type',
            'text': 'text'
        }

        self._type = type
        self._text = text

    @classmethod
    def from_dict(cls, dikt) -> 'ChatCompletionRequestToolMessageContentPart':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ChatCompletionRequestToolMessageContentPart of this ChatCompletionRequestToolMessageContentPart.  # noqa: E501
        :rtype: ChatCompletionRequestToolMessageContentPart
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this ChatCompletionRequestToolMessageContentPart.

        The type of the content part.  # noqa: E501

        :return: The type of this ChatCompletionRequestToolMessageContentPart.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this ChatCompletionRequestToolMessageContentPart.

        The type of the content part.  # noqa: E501

        :param type: The type of this ChatCompletionRequestToolMessageContentPart.
        :type type: str
        """
        allowed_values = ["text"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def text(self) -> str:
        """Gets the text of this ChatCompletionRequestToolMessageContentPart.

        The text content.  # noqa: E501

        :return: The text of this ChatCompletionRequestToolMessageContentPart.
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text: str):
        """Sets the text of this ChatCompletionRequestToolMessageContentPart.

        The text content.  # noqa: E501

        :param text: The text of this ChatCompletionRequestToolMessageContentPart.
        :type text: str
        """
        if text is None:
            raise ValueError("Invalid value for `text`, must not be `None`")  # noqa: E501

        self._text = text
